import {
  project0,
  projectZero,
  project1,
  projectOne,
  project2,
  projectTwo,
  project3,
  projectThree,
  project6,
  projectSix,
  project7,
  projectSeven,
  project8,
  projectEight,
  project9,
  projectNine,
  project10,
  projectTen,
  project11,
  projectEleven,
  project12,
  projectTwelve,
  project13,
  projectThirteen,
  project14,
  projectFourteen,
  project15,
  projectFifteen,
  project16,
  projectSixteen,
  project17,
  projectSeventeen,
} from './projectImages';

export const projectData = [
    {
        id: 0,
        image: project0,
        transitionImage: projectZero,
        title: "Quiz App",
        codeLink: "https://github.com/martinmorondo/Quiz-app",
        liveLink: "https://fabulous-chebakia-16e5f0.netlify.app/",
      },
      {
        id: 1,
        image: project1,
        transitionImage: projectOne,
        title: "Whack a mole game",
        codeLink: "https://github.com/martinmorondo/Whack-a-mole-game",
        liveLink: "https://marvelous-lamington-597fcd.netlify.app/",
      },
      {
        id: 2,
        image: project2,
        transitionImage: projectTwo,
        title: "Own Webpage",
        codeLink: "https://github.com/martinmorondo/My-website",
        liveLink: "https://recursosparaprogramadores.netlify.app/",
      },
      {
        id: 3,
        image: project3,
        transitionImage: projectThree,
        title: "JS Puzzle",
        codeLink: "https://github.com/martinmorondo/Puzzle",
        liveLink: "https://magical-sprinkles-54dc75.netlify.app/",
      },
      // {
      //   id: 4,
      //   image: project4,
      //   transitionImage: projectFour,
      //   title: "Movie App",
      //   codeLink: "https://github.com/martinmorondo/movie-app",
      //   liveLink: "https://scintillating-mooncake-f1005a.netlify.app",
      // },
      // {
      //   id: 5,
      //   image: project5,
      //   transitionImage: projectFive,
      //   title: "TODO App",
      //   codeLink: "https://github.com/martinmorondo/Lista-de-Tareas",
      //   liveLink: "https://fluffy-cocada-9c2f2e.netlify.app/",
      // },
      {
        id: 6,
        image: project6,
        transitionImage: projectSix,
        title: "JS Ecommerce",
        codeLink: "https://github.com/martinmorondo/Ecommerce",
        liveLink: "https://mellifluous-cupcake-82cef1.netlify.app/",
      },
      {
        id: 7,
        image: project7,
        transitionImage: projectSeven,
        title: "React Weather App",
        codeLink: "https://github.com/martinmorondo/proyect-react-weatherApp",
        liveLink: "https://superlative-madeleine-ddfbfa.netlify.app/",
      },
      {
        id: 8,
        image: project8,
        transitionImage: projectEight,
        title: "Twitter Follow Card",
        codeLink: "https://github.com/martinmorondo/react-twitter-follow-card",
        liveLink: "https://genuine-cajeta-a582bc.netlify.app/",
      },
      {
        id: 9,
        image: project9,
        transitionImage: projectNine,
        title: "React Gym",
        codeLink: "https://github.com/martinmorondo/react-gym",
        liveLink: "https://helpful-halva-c2f9db.netlify.app/",
      },
      {
        id: 10,
        image: project10,
        transitionImage: projectTen,
        title: "Tic Tac Toe Game",
        codeLink: "https://github.com/martinmorondo/tic-tac-toe-game",
        liveLink: "https://velvety-dragon-098b69.netlify.app/",
      },
      {
        id: 11,
        image: project11,
        transitionImage: projectEleven,
        title: "React Grocery Budget",
        codeLink: "https://github.com/martinmorondo/react-grocery-budget-",
        liveLink: "https://tourmaline-jalebi-9f1956.netlify.app/",
      },
      {
        id: 12,
        image: project12,
        transitionImage: projectTwelve,
        title: "React Tours",
        codeLink: "https://github.com/martinmorondo/react-tours",
        liveLink: "https://iridescent-bienenstitch-08c89c.netlify.app/",
      },
      {
        id: 13,
        image: project13,
        transitionImage: projectThirteen,
        title: "Question Game",
        codeLink: "https://github.com/martinmorondo/question-game",
        liveLink: "https://whimsical-basbousa-8f71a8.netlify.app/",
      },
      {
        id: 14,
        image: project14,
        transitionImage: projectFourteen,
        title: "Reflex Game",
        codeLink: "https://github.com/martinmorondo/reflex-game",
        liveLink: "https://sparkly-dolphin-dea9fa.netlify.app/",
      },
      {
        id: 15,
        image: project15,
        transitionImage: projectFifteen,
        title: "React Shopping",
        codeLink: "https://github.com/martinmorondo/react-shopping-cart",
        liveLink: "https://fastidious-cendol-ad104b.netlify.app/",
      },
      {
        id: 16,
        image: project16,
        transitionImage: projectSixteen,
        title: "React Ecommerce",
        codeLink: "https://github.com/martinmorondo/react-ecommerce",
        liveLink: "https://lively-dasik-84407c.netlify.app/",
      },
       {
        id: 17,
        image: project17,
        transitionImage: projectSeventeen,
        title: "React Chatbot",
        codeLink: "https://github.com/martinmorondo/portfolio-chatbot",
        liveLink: "https://bucolic-praline-a0d151.netlify.app/",
      },
]